name: Azure Static Web Apps CI/CD
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build And Deploy
        env:
          REACT_APP_GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_MEASUREMENT_ID }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          api_location: "" 
          # This is enough for now to get the app running
